### Create a USER 1
POST http://localhost:3000/users
Content-Type: application/json

{
  "user_name": "Bob",
  "user_email" : "bob@dsdsdewsadsdsdsadsdsdsemreail.com",
  "user_password": "bob",
  "user_mobile": "0953263665",
  "user_firstname": "nontapat",
  "user_lastname": "kruprucha"
}
### Create a USER 2
POST http://localhost:3000/users
Content-Type: application/json

{
  "user_name": "Fred",
  "user_email" : "fred@email.com",
  "user_password": "fred",
  "user_firstname": "nontapat",
  "user_lastname": "kruprucha",
  "user_nickname": "kru"

}

###List USERS
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTA5NjQ2NzEsImV4cCI6MTY1MDk2NDk3MX0.ReHWmNujhmg_zzZfp-aO-ZZSYvv_RZ68O8mdbdnmeIM
###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email":"fred@email.com",
  "password":"fred"
}
####
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email":"flukgoza@gmail.com",
  "password":"1234"
}

###REFRESH TOKENS
GET http://localhost:5000/api/auth/refresh_token

###

DELETE http://localhost:3000/auth/refresh_token
###

DELETE http://localhost:3000/users
Content-Type: application/json

{
  "user_email" : "bob@email.com"
}
###